// <auto-generated />
namespace ContosoUniversity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class DisplayWithSpaces : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DisplayWithSpaces));
        
        string IMigrationMetadata.Id
        {
            get { return "202002151725121_DisplayWithSpaces"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
